stages:
  data_ingestion:
    cmd: python src/CNN_Classifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/CNN_Classifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney-ct-scan-image


  prepare_base_model:
    cmd: python src/CNN_Classifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/CNN_Classifier/pipeline/stage_02_prepare_base_model.py
      - config//config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model